version: 2
jobs:
  build:
    working_directory: ~/cornelius
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
        requires:
          - build
